from snakemake.utils import min_version

##### set minimum snakemake version #####
min_version("8.4.1")


#containerized: "docker://ghcr.io/ht-diva/pqtl_pipeline:d0d53c1"

configfile: "config/config.yaml"
config_copy="config/config.yaml"


include: "rules/common.smk"
include: "rules/return_config.smk"


rule all:
    input:
        ws_path("susierss/combined_credibles.tsv"),
        ws_path("config/config_used.yaml"),


if config.get("run").get("susier"):

    include: "rules/subset_gwas.smk"
    include: "rules/subset_pgen.smk"
    include: "rules/compute_ld.smk"
    include: "rules/finemapping.smk"

else:

    include: "rules/query_gwas.smk"
    include: "rules/extrating_pheno.smk"
    include: "rules/subset_pgen.smk"
    include: "rules/compute_ld.smk"
    include: "rules/finemapping.smk"

