from snakemake.utils import min_version

##### set minimum snakemake version #####
min_version("8.4.1")


#containerized: "docker://ghcr.io/ht-diva/pqtl_pipeline:d0d53c1"

configfile: "config/config.yaml"


include: "rules/common.smk"


rule all:
    input:
        #expand(ws_path("tmp/{locuseq}_snps.list"), locuseq = data.locuseq),
        #expand(ws_path("tmp/{locuseq}_dosage.pgen"), locuseq = data.locuseq),
        #expand(ws_path("susierss/cs_list/{locuseq}.cslist"), locuseq = data.locuseq),
        ws_path("susierss/collected_credible_sets.tsv"),
        #expand(ws_path("tmp/{locuseq}_pheno.csv"), locuseq = data.locuseq)
        #expand(ws_path("tmp/{locuseq}_query.yaml"), locuseq = data.locuseq),
        #expand(ws_path("tmp/{locuseq}/{locuseq}_sumstat.csv.gz"), locuseq = data.locuseq)


if config.get("run").get("susier"):

    include: "rules/subset_gwas.smk"
    include: "rules/subset_pgen.smk"
    include: "rules/compute_ld.smk"
    include: "rules/finemapping.smk"

else:

    include: "rules/query_gwas.smk"
    include: "rules/extrating_pheno.smk"
    include: "rules/subset_pgen.smk"
    include: "rules/compute_ld.smk"
    include: "rules/finemapping.smk"
    

# rule all:
#     input:
#         get_final_output(),
#     resources:
#         runtime=3,