executor: slurm
jobs: 250
software-deployment-method:
   - conda
   - apptainer
retries: 0
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
cores: &cores 4
latency-wait: 60
keep-going: True
rerun-incomplete: False
printshellcmds: True
scheduler: ilp


default-resources:
    slurm_partition: cpuq
    # slurm_account: ${USER}
    mem_mb: attempt * 512
    threads: 1
    runtime: attempt * 5
set-threads:
    harmonize_sumstats: *cores
    bgzip_tabix: *cores
set-resources:
    extract_dosage:
        mem_mb: 8000 + attempt * 2048
        threads: *cores
    run_susieR:
        mem_mb: 500 + attempt * 2048
        threads: *cores
    collect_credible_sets:
        mem_mb: 4000 + attempt * 2048