run:
  susie: False
  susier: True

 # The pipe will enable the use of correlation matrix based on LD as specified in link below:
 # https://stephenslab.github.io/susieR/articles/finemapping_summary_statistics.html
 # If set to False (default), it will use the genotypes coded with additive model
 # together with the phenotype to evaluate the RSS model.


# paths
workspace_path: "results/VTN_interval"
path_lb: "config/VTN_interval.csv"
#path_gwas: "/exchange/healthds/pQTL/results/META_CHRIS_INTERVAL/qced_sumstats_digits_not_flipped_filtered/output"
path_gwas: "/exchange/healthds/pQTL/results/INTERVAL/chunk_1083/chunk_1083_output/chunk_1083/results/gwas"
genotype: "/scratch/giulia.pontali/genomics_QC_pipeline/results_scratch/pgen/qc_recoded_harmonised/impute_recoded_selected_sample_filter_hq_var_new_id_alleles_"
phenotype: "/exchange/healthds/pQTL/INTERVAL/residuals/INTERVAL_NonImp_residuals_final.txt"


sumstat:
  pvalcol: "LOG10P"
  snpcol: "ID"
  chrcol: "CHROM"



# Phenotype file used in the GWAS
# ============================= #
# tab separated.
# First two colums should be FID and IID
#pheno_file: "data/INTERVAL_NonImp_residuals_final.txt"
#run_list: "data/pheno_to_run.csv"
#sample_file: "data/samplelist.csv"


# SusieR parameters
susieR:
 min_abs_corr: 0.1
 iter: 1000
 extension: 0

