run:
  susie: False
  susier: True
  ld_correlation: False

# paths
workspace_path: "results/interval_cis_b38"
path_lb: "/home/dariush.ghasemi/13-Apr-26_collected_loci_interval_cis.csv"
path_gwas: "/exchange/healthds/pQTL/results/INTERVAL/qced_sumstats/outputs"
genotype: "/exchange/healthds/pQTL/INTERVAL/Genetic_QC_files/pgen/qc_recoded_harmonised/impute_recoded_selected_sample_filter_hq_var_new_id_alleles_"
path_pheno: "data/INTERVAL_NonImp_residuals_final.txt"
genomic_key: "/scratch/dariush.ghasemi/projects/pqtl_liftover/results/interval_harm/VCF_lifted/lifted_variants.txt"


sumstat:
  pvalcol: "MLOG10P"
  snpcol: "SNPID"
  chrcol: "CHR"


# SusieR parameters
susieR:
 min_abs_corr: 0.5
 iter: 1000
 L: 10
 extension: 100000
 estimate_residual_variance: FALSE

